database {
    url = ${DB_URL}
    driver = "com.mysql.cj.jdbc.Driver"
    user = "root"
    password = ${DB_ROOT_PASSWORD}
}

ktor {
    deployment {
        log = true
        loglevel = INFO
    }
}