database {
    url = "jdbc:mysql://127.0.0.1:3307/volunteer" // ${DB_URL}
    driver = "com.mysql.cj.jdbc.Driver"
    user = "root"
    password = "MyNewPass123!"// ${DB_ROOT_PASSWORD}
}

ktor {
    deployment {
        log = true
        loglevel = INFO
    }
}