database {
    url = ${?DB_URL} "jdbc:mysql://127.0.0.1:3306/volunteer?useSSL=false&allowPublicKeyRetrieval=true"
    driver = "com.mysql.cj.jdbc.Driver"
    user = "root"
    password = "MyNewPass123!"
}

ktor {
    deployment {
        log = true
        loglevel = INFO
    }
}